namespace Obfuscation.Core.Mappers
{
    internal static class CSParserState
    {
        public static string IndexToName(int stateCode)
        {
            switch (stateCode)
            {
                case 403: return "extern_alias_directives";
                case 406: return "using_directives";
                case 409: return "global_attribute_section";
                case 415: return "namespace_member_declarations";
                case 420: return "identifier";
                case 421: return "type_argument_list";
                case 424: return "qualified_alias_member";
                case 428: return "identifier";
                case 429: return "type_argument_list";
                case 437: return "base_type";
                case 439: return "rank_specifier";
                case 446: return "simple_type";
                case 447: return "class_type";
                case 452: return "numeric_type";
                case 456: return "integral_type";
                case 457: return "floating_point_type";
                case 465: return "namespace_or_type_name";
                case 472: return "type";
                case 474: return "type";
                case 482: return "argument";
                case 484: return "argument";
                case 490: return "identifier";
                case 498: return "expression";
                case 500: return "assignment";
                case 501: return "non_assignment_expression";
                case 504: return "lambda_expression";
                case 505: return "query_expression";
                case 506: return "conditional_expression";
                case 509: return "unary_expression";
                case 510: return "assignment_operator";
                case 511: return "expression";
                case 523: return "right_shift_assignment";
                case 526: return "null_coalescing_expression";
                case 528: return "expression";
                case 530: return "expression";
                case 534: return "conditional_or_expression";
                case 536: return "null_coalescing_expression";
                case 539: return "conditional_and_expression";
                case 541: return "conditional_and_expression";
                case 547: return "inclusive_or_expression";
                case 549: return "inclusive_or_expression";
                case 555: return "exclusive_or_expression";
                case 557: return "exclusive_or_expression";
                case 563: return "and_expression";
                case 565: return "and_expression";
                case 571: return "equality_expression";
                case 573: return "equality_expression";
                case 579: return "relational_expression";
                case 581: return "relational_expression";
                case 587: return "shift_expression";
                case 589: return "shift_expression";
                case 591: return "isType";
                case 593: return "type";
                case 599: return "additive_expression";
                case 601: return "right_shift";
                case 604: return "additive_expression";
                case 610: return "multiplicative_expression";
                case 612: return "multiplicative_expression";
                case 618: return "unary_expression";
                case 620: return "unary_expression";
                case 626: return "primary_expression";
                case 628: return "unary_expression";
                case 630: return "unary_expression";
                case 632: return "unary_expression";
                case 634: return "unary_expression";
                case 636: return "unary_expression";
                case 638: return "unary_expression";
                case 640: return "type";
                case 642: return "unary_expression";
                case 645: return "unary_expression";
                case 647: return "unary_expression";
                case 649: return "unary_expression";
                case 652: return "primary_expression_start";
                case 653: return "bracket_expression";
                case 659: return "member_access";
                case 660: return "method_invocation";
                case 664: return "identifier";
                case 667: return "bracket_expression";
                case 678: return "literal";
                case 679: return "identifier";
                case 680: return "type_argument_list";
                case 684: return "expression";
                case 687: return "predefined_type";
                case 688: return "qualified_alias_member";
                case 693: return "identifier";
                case 694: return "type_argument_list";
                case 698: return "expression_list";
                case 704: return "type";
                case 705: return "object_creation_expression";
                case 706: return "object_or_collection_initializer";
                case 708: return "expression_list";
                case 710: return "rank_specifier";
                case 716: return "array_initializer";
                case 719: return "rank_specifier";
                case 724: return "array_initializer";
                case 728: return "anonymous_object_initializer";
                case 729: return "rank_specifier";
                case 730: return "array_initializer";
                case 736: return "unbound_type_name";
                case 737: return "type";
                case 744: return "expression";
                case 749: return "expression";
                case 754: return "type";
                case 762: return "explicit_anonymous_function_parameter_list";
                case 768: return "block";
                case 771: return "type";
                case 776: return "identifier";
                case 784: return "identifier";
                case 793: return "identifier";
                case 794: return "type_argument_list";
                case 801: return "indexer_argument";
                case 803: return "indexer_argument";
                case 811: return "identifier";
                case 816: return "expression";
                case 820: return "expression";
                case 822: return "expression";
                case 828: return "object_initializer";
                case 829: return "collection_initializer";
                case 833: return "member_initializer_list";
                case 841: return "member_initializer";
                case 843: return "member_initializer";
                case 849: return "identifier";
                case 851: return "expression";
                case 857: return "initializer_value";
                case 859: return "expression";
                case 860: return "object_or_collection_initializer";
                case 864: return "element_initializer";
                case 866: return "element_initializer";
                case 877: return "non_assignment_expression";
                case 879: return "expression_list";
                case 885: return "member_declarator_list";
                case 893: return "member_declarator";
                case 895: return "member_declarator";
                case 901: return "primary_expression";
                case 902: return "identifier";
                case 904: return "expression";
                case 908: return "identifier";
                case 909: return "generic_dimension_specifier";
                case 913: return "identifier";
                case 914: return "generic_dimension_specifier";
                case 920: return "identifier";
                case 921: return "generic_dimension_specifier";
                case 938: return "base_type";
                case 939: return "rank_specifier";
                case 952: return "anonymous_function_signature";
                case 953: return "right_arrow";
                case 954: return "anonymous_function_body";
                case 959: return "explicit_anonymous_function_parameter_list";
                case 963: return "implicit_anonymous_function_parameter_list";
                case 966: return "identifier";
                case 969: return "explicit_anonymous_function_parameter";
                case 971: return "explicit_anonymous_function_parameter";
                case 980: return "type";
                case 981: return "identifier";
                case 983: return "identifier";
                case 985: return "identifier";
                case 991: return "expression";
                case 992: return "block";
                case 995: return "from_clause";
                case 996: return "query_body";
                case 999: return "type";
                case 1002: return "identifier";
                case 1004: return "expression";
                case 1006: return "query_body_clause";
                case 1012: return "select_or_group_clause";
                case 1013: return "query_continuation";
                case 1016: return "from_clause";
                case 1017: return "let_clause";
                case 1018: return "where_clause";
                case 1019: return "combined_join_clause";
                case 1020: return "orderby_clause";
                case 1024: return "identifier";
                case 1026: return "expression";
                case 1029: return "expression";
                case 1032: return "type";
                case 1035: return "identifier";
                case 1037: return "expression";
                case 1039: return "expression";
                case 1041: return "expression";
                case 1043: return "identifier";
                case 1047: return "ordering";
                case 1049: return "ordering";
                case 1055: return "expression";
                case 1060: return "expression";
                case 1062: return "expression";
                case 1064: return "expression";
                case 1069: return "identifier";
                case 1070: return "query_body";
                case 1072: return "identifier";
                case 1074: return "statement";
                case 1076: return "local_variable_declaration";
                case 1077: return "local_constant_declaration";
                case 1082: return "embedded_statement";
                case 1085: return "block";
                case 1086: return "simple_embedded_statement";
                case 1090: return "expression";
                case 1095: return "expression";
                case 1097: return "if_body";
                case 1099: return "if_body";
                case 1104: return "expression";
                case 1107: return "switch_section";
                case 1117: return "expression";
                case 1119: return "embedded_statement";
                case 1122: return "embedded_statement";
                case 1125: return "expression";
                case 1131: return "for_initializer";
                case 1135: return "expression";
                case 1139: return "for_iterator";
                case 1143: return "embedded_statement";
                case 1146: return "type";
                case 1147: return "identifier";
                case 1149: return "expression";
                case 1151: return "embedded_statement";
                case 1158: return "identifier";
                case 1160: return "expression";
                case 1166: return "expression";
                case 1171: return "expression";
                case 1176: return "block";
                case 1177: return "catch_clauses";
                case 1178: return "finally_clause";
                case 1181: return "finally_clause";
                case 1185: return "block";
                case 1187: return "block";
                case 1190: return "expression";
                case 1192: return "embedded_statement";
                case 1196: return "resource_acquisition";
                case 1198: return "embedded_statement";
                case 1202: return "expression";
                case 1208: return "block";
                case 1211: return "pointer_type";
                case 1212: return "fixed_pointer_declarators";
                case 1214: return "embedded_statement";
                case 1219: return "statement_list";
                case 1224: return "type";
                case 1225: return "local_variable_declarator";
                case 1227: return "local_variable_declarator";
                case 1233: return "identifier";
                case 1235: return "local_variable_initializer";
                case 1238: return "expression";
                case 1239: return "array_initializer";
                case 1240: return "local_variable_initializer_unsafe";
                case 1244: return "type";
                case 1245: return "constant_declarators";
                case 1247: return "block";
                case 1248: return "simple_embedded_statement";
                case 1251: return "switch_label";
                case 1256: return "statement_list";
                case 1259: return "expression";
                case 1266: return "statement";
                case 1271: return "local_variable_declaration";
                case 1272: return "expression";
                case 1274: return "expression";
                case 1282: return "expression";
                case 1284: return "expression";
                case 1290: return "specific_catch_clause";
                case 1291: return "specific_catch_clause";
                case 1297: return "general_catch_clause";
                case 1300: return "general_catch_clause";
                case 1305: return "class_type";
                case 1306: return "identifier";
                case 1310: return "exception_filter";
                case 1313: return "block";
                case 1316: return "exception_filter";
                case 1319: return "block";
                case 1323: return "expression";
                case 1327: return "block";
                case 1329: return "local_variable_declaration";
                case 1330: return "expression";
                case 1334: return "qualified_identifier";
                case 1335: return "namespace_body";
                case 1339: return "identifier";
                case 1341: return "identifier";
                case 1348: return "extern_alias_directives";
                case 1351: return "using_directives";
                case 1354: return "namespace_member_declarations";
                case 1359: return "extern_alias_directive";
                case 1366: return "identifier";
                case 1369: return "using_directive";
                case 1375: return "identifier";
                case 1377: return "namespace_or_type_name";
                case 1381: return "namespace_or_type_name";
                case 1386: return "namespace_or_type_name";
                case 1391: return "namespace_member_declaration";
                case 1396: return "namespace_declaration";
                case 1397: return "type_declaration";
                case 1400: return "attributes";
                case 1403: return "all_member_modifiers";
                case 1406: return "class_definition";
                case 1407: return "struct_definition";
                case 1408: return "interface_definition";
                case 1409: return "enum_definition";
                case 1410: return "delegate_definition";
                case 1413: return "identifier";
                case 1415: return "identifier";
                case 1416: return "type_argument_list";
                case 1420: return "type_parameter";
                case 1422: return "type_parameter";
                case 1430: return "attributes";
                case 1433: return "identifier";
                case 1436: return "class_type";
                case 1438: return "namespace_or_type_name";
                case 1444: return "namespace_or_type_name";
                case 1446: return "namespace_or_type_name";
                case 1452: return "type_parameter_constraints_clause";
                case 1458: return "identifier";
                case 1460: return "type_parameter_constraints";
                case 1462: return "constructor_constraint";
                case 1463: return "primary_constraint";
                case 1465: return "secondary_constraints";
                case 1469: return "constructor_constraint";
                case 1474: return "class_type";
                case 1479: return "namespace_or_type_name";
                case 1481: return "namespace_or_type_name";
                case 1492: return "class_member_declarations";
                case 1497: return "class_member_declaration";
                case 1502: return "attributes";
                case 1505: return "all_member_modifiers";
                case 1508: return "common_member_declaration";
                case 1509: return "destructor_definition";
                case 1512: return "all_member_modifier";
                case 1519: return "constant_declaration";
                case 1520: return "typed_member_declaration";
                case 1521: return "event_declaration";
                case 1522: return "conversion_operator_declarator";
                case 1523: return "body";
                case 1524: return "right_arrow";
                case 1525: return "expression";
                case 1530: return "constructor_declaration";
                case 1532: return "method_declaration";
                case 1533: return "class_definition";
                case 1534: return "struct_definition";
                case 1535: return "interface_definition";
                case 1536: return "enum_definition";
                case 1537: return "delegate_definition";
                case 1540: return "type";
                case 1541: return "namespace_or_type_name";
                case 1543: return "indexer_declaration";
                case 1545: return "method_declaration";
                case 1546: return "property_declaration";
                case 1547: return "indexer_declaration";
                case 1548: return "operator_declaration";
                case 1549: return "field_declaration";
                case 1552: return "constant_declarator";
                case 1554: return "constant_declarator";
                case 1560: return "identifier";
                case 1562: return "expression";
                case 1564: return "variable_declarator";
                case 1566: return "variable_declarator";
                case 1572: return "identifier";
                case 1574: return "variable_initializer";
                case 1577: return "expression";
                case 1578: return "array_initializer";
                case 1581: return "type";
                case 1585: return "namespace_or_type_name";
                case 1587: return "block";
                case 1591: return "parameter_array";
                case 1592: return "fixed_parameters";
                case 1594: return "parameter_array";
                case 1599: return "fixed_parameter";
                case 1601: return "fixed_parameter";
                case 1607: return "attributes";
                case 1610: return "parameter_modifier";
                case 1613: return "arg_declaration";
                case 1619: return "attributes";
                case 1623: return "array_type";
                case 1624: return "identifier";
                case 1626: return "attributes";
                case 1629: return "accessor_modifier";
                case 1633: return "accessor_body";
                case 1634: return "set_accessor_declaration";
                case 1638: return "accessor_body";
                case 1639: return "get_accessor_declaration";
                case 1644: return "attributes";
                case 1647: return "accessor_modifier";
                case 1651: return "accessor_body";
                case 1653: return "attributes";
                case 1656: return "accessor_modifier";
                case 1660: return "accessor_body";
                case 1671: return "block";
                case 1675: return "attributes";
                case 1679: return "block";
                case 1680: return "remove_accessor_declaration";
                case 1683: return "block";
                case 1684: return "add_accessor_declaration";
                case 1688: return "attributes";
                case 1692: return "block";
                case 1694: return "attributes";
                case 1698: return "block";
                case 1715: return "right_shift";
                case 1726: return "type";
                case 1728: return "arg_declaration";
                case 1734: return "argument_list";
                case 1739: return "block";
                case 1744: return "interface_type_list";
                case 1747: return "struct_member_declaration";
                case 1755: return "attributes";
                case 1758: return "all_member_modifiers";
                case 1761: return "common_member_declaration";
                case 1763: return "type";
                case 1764: return "fixed_size_buffer_declarator";
                case 1773: return "base_type";
                case 1780: return "rank_specifier";
                case 1795: return "variable_initializer";
                case 1797: return "variable_initializer";
                case 1811: return "variant_type_parameter";
                case 1813: return "variant_type_parameter";
                case 1821: return "attributes";
                case 1824: return "variance_annotation";
                case 1827: return "identifier";
                case 1832: return "interface_type_list";
                case 1835: return "interface_member_declaration";
                case 1843: return "attributes";
                case 1852: return "type";
                case 1853: return "identifier";
                case 1854: return "type_parameter_list";
                case 1858: return "formal_parameter_list";
                case 1862: return "type_parameter_constraints_clauses";
                case 1867: return "identifier";
                case 1869: return "interface_accessors";
                case 1874: return "formal_parameter_list";
                case 1877: return "interface_accessors";
                case 1886: return "identifier";
                case 1887: return "type_parameter_list";
                case 1891: return "formal_parameter_list";
                case 1895: return "type_parameter_constraints_clauses";
                case 1901: return "type";
                case 1902: return "identifier";
                case 1907: return "attributes";
                case 1912: return "attributes";
                case 1921: return "attributes";
                case 1931: return "type";
                case 1934: return "enum_member_declaration";
                case 1936: return "enum_member_declaration";
                case 1949: return "attributes";
                case 1952: return "identifier";
                case 1954: return "expression";
                case 1958: return "global_attribute_target";
                case 1960: return "attribute_list";
                case 1966: return "keyword";
                case 1967: return "identifier";
                case 1970: return "attribute_section";
                case 1976: return "attribute_target";
                case 1981: return "attribute_list";
                case 1987: return "keyword";
                case 1988: return "identifier";
                case 1991: return "attribute";
                case 1993: return "attribute";
                case 1999: return "namespace_or_type_name";
                case 2001: return "attribute_argument";
                case 2003: return "attribute_argument";
                case 2014: return "identifier";
                case 2019: return "expression";
                case 2021: return "simple_type";
                case 2022: return "class_type";
                case 2025: return "rank_specifier";
                case 2038: return "fixed_pointer_declarator";
                case 2040: return "fixed_pointer_declarator";
                case 2046: return "identifier";
                case 2048: return "fixed_pointer_initializer";
                case 2053: return "expression";
                case 2054: return "local_variable_initializer_unsafe";
                case 2057: return "identifier";
                case 2059: return "expression";
                case 2063: return "type";
                case 2065: return "expression";
                case 2080: return "boolean_literal";
                case 2081: return "string_literal";
                case 2091: return "interpolated_regular_string";
                case 2092: return "interpolated_verbatium_string";
                case 2098: return "interpolated_regular_string_part";
                case 2107: return "interpolated_verbatium_string_part";
                case 2115: return "interpolated_string_expression";
                case 2121: return "interpolated_string_expression";
                case 2127: return "expression";
                case 2129: return "expression";
                case 2146: return "identifier";
                case 2147: return "type_parameter_list";
                case 2150: return "class_base";
                case 2153: return "type_parameter_constraints_clauses";
                case 2156: return "class_body";
                case 2161: return "identifier";
                case 2162: return "type_parameter_list";
                case 2165: return "struct_interfaces";
                case 2168: return "type_parameter_constraints_clauses";
                case 2171: return "struct_body";
                case 2176: return "identifier";
                case 2177: return "variant_type_parameter_list";
                case 2180: return "interface_base";
                case 2183: return "type_parameter_constraints_clauses";
                case 2186: return "interface_body";
                case 2191: return "identifier";
                case 2192: return "enum_base";
                case 2195: return "enum_body";
                case 2200: return "return_type";
                case 2201: return "identifier";
                case 2202: return "variant_type_parameter_list";
                case 2206: return "formal_parameter_list";
                case 2210: return "type_parameter_constraints_clauses";
                case 2216: return "type";
                case 2217: return "variable_declarators";
                case 2220: return "member_name";
                case 2222: return "event_accessor_declarations";
                case 2227: return "variable_declarators";
                case 2230: return "member_name";
                case 2232: return "accessor_declarations";
                case 2235: return "variable_initializer";
                case 2240: return "right_arrow";
                case 2241: return "expression";
                case 2247: return "type";
                case 2248: return "constant_declarators";
                case 2253: return "formal_parameter_list";
                case 2256: return "accessor_declarations";
                case 2259: return "right_arrow";
                case 2260: return "expression";
                case 2266: return "identifier";
                case 2269: return "body";
                case 2271: return "identifier";
                case 2273: return "formal_parameter_list";
                case 2277: return "constructor_initializer";
                case 2280: return "body";
                case 2282: return "method_member_name";
                case 2283: return "type_parameter_list";
                case 2287: return "formal_parameter_list";
                case 2291: return "type_parameter_constraints_clauses";
                case 2294: return "method_body";
                case 2295: return "right_arrow";
                case 2296: return "expression";
                case 2301: return "identifier";
                case 2302: return "identifier";
                case 2304: return "identifier";
                case 2308: return "type_argument_list";
                case 2312: return "identifier";
                case 2319: return "overloadable_operator";
                case 2321: return "arg_declaration";
                case 2323: return "arg_declaration";
                case 2327: return "body";
                case 2328: return "right_arrow";
                case 2329: return "expression";
                case 2334: return "type";
                case 2335: return "identifier";
                case 2337: return "expression";
                case 2341: return "argument_list";
                case 2347: return "argument_list";
                case 2351: return "object_or_collection_initializer";

                default: return null;
            }
        }

        public static int[] NameToIndex(string name)
        {
            switch (name.ToLower())
            {
                case "istype": return new int[] { 591 };
                case "extern_alias_directives": return new int[] { 403, 1348 };
                case "using_directives": return new int[] { 406, 1351 };
                case "global_attribute_section": return new int[] { 409 };
                case "namespace_member_declarations": return new int[] { 415, 1354 };
                case "identifier": return new int[] { 420, 428, 490, 664, 679, 693, 776, 784, 793, 811, 849, 902, 908, 913, 920, 966, 981, 983, 985, 1002, 1024, 1035, 1043, 1069, 1072, 1147, 1158, 1233, 1306, 1339, 1341, 1366, 1375, 1413, 1415, 1433, 1458, 1560, 1572, 1624, 1827, 1853, 1867, 1886, 1902, 1952, 1967, 1988, 2014, 2046, 2057, 2146, 2161, 2176, 2191, 2201, 2266, 2271, 2301, 2302, 2304, 2312, 2335 };
                case "type_argument_list": return new int[] { 421, 429, 680, 694, 794, 1416, 2308 };
                case "qualified_alias_member": return new int[] { 424, 688 };
                case "base_type": return new int[] { 437, 938, 1773 };
                case "rank_specifier": return new int[] { 439, 710, 719, 729, 939, 1780, 2025 };
                case "simple_type": return new int[] { 446, 2021 };
                case "class_type": return new int[] { 447, 1305, 1436, 1474, 2022 };
                case "numeric_type": return new int[] { 452 };
                case "integral_type": return new int[] { 456 };
                case "floating_point_type": return new int[] { 457 };
                case "namespace_or_type_name": return new int[] { 465, 1377, 1381, 1386, 1438, 1444, 1446, 1479, 1481, 1541, 1585, 1999 };
                case "type": return new int[] { 472, 474, 593, 640, 704, 737, 754, 771, 980, 999, 1032, 1146, 1224, 1244, 1540, 1581, 1726, 1763, 1852, 1901, 1931, 2063, 2216, 2247, 2334 };
                case "argument": return new int[] { 482, 484 };
                case "expression": return new int[] { 498, 511, 528, 530, 684, 744, 749, 816, 820, 822, 851, 859, 904, 991, 1004, 1026, 1029, 1037, 1039, 1041, 1055, 1060, 1062, 1064, 1090, 1095, 1104, 1117, 1125, 1135, 1149, 1160, 1166, 1171, 1190, 1202, 1238, 1259, 1272, 1274, 1282, 1284, 1323, 1330, 1525, 1562, 1577, 1954, 2019, 2053, 2059, 2065, 2127, 2129, 2241, 2260, 2296, 2329, 2337 };
                case "assignment": return new int[] { 500 };
                case "non_assignment_expression": return new int[] { 501, 877 };
                case "lambda_expression": return new int[] { 504 };
                case "query_expression": return new int[] { 505 };
                case "conditional_expression": return new int[] { 506 };
                case "unary_expression": return new int[] { 509, 618, 620, 628, 630, 632, 634, 636, 638, 642, 645, 647, 649 };
                case "assignment_operator": return new int[] { 510 };
                case "right_shift_assignment": return new int[] { 523 };
                case "null_coalescing_expression": return new int[] { 526, 536 };
                case "conditional_or_expression": return new int[] { 534 };
                case "conditional_and_expression": return new int[] { 539, 541 };
                case "inclusive_or_expression": return new int[] { 547, 549 };
                case "exclusive_or_expression": return new int[] { 555, 557 };
                case "and_expression": return new int[] { 563, 565 };
                case "equality_expression": return new int[] { 571, 573 };
                case "relational_expression": return new int[] { 579, 581 };
                case "shift_expression": return new int[] { 587, 589 };
                case "additive_expression": return new int[] { 599, 604 };
                case "right_shift": return new int[] { 601, 1715 };
                case "multiplicative_expression": return new int[] { 610, 612 };
                case "primary_expression": return new int[] { 626, 901 };
                case "primary_expression_start": return new int[] { 652 };
                case "bracket_expression": return new int[] { 653, 667 };
                case "member_access": return new int[] { 659 };
                case "method_invocation": return new int[] { 660 };
                case "literal": return new int[] { 678 };
                case "predefined_type": return new int[] { 687 };
                case "expression_list": return new int[] { 698, 708, 879 };
                case "object_creation_expression": return new int[] { 705 };
                case "object_or_collection_initializer": return new int[] { 706, 860, 2351 };
                case "array_initializer": return new int[] { 716, 724, 730, 1239, 1578 };
                case "anonymous_object_initializer": return new int[] { 728 };
                case "unbound_type_name": return new int[] { 736 };
                case "explicit_anonymous_function_parameter_list": return new int[] { 762, 959 };
                case "block": return new int[] { 768, 992, 1085, 1176, 1185, 1187, 1208, 1247, 1313, 1319, 1327, 1587, 1671, 1679, 1683, 1692, 1698, 1739 };
                case "indexer_argument": return new int[] { 801, 803 };
                case "object_initializer": return new int[] { 828 };
                case "collection_initializer": return new int[] { 829 };
                case "member_initializer_list": return new int[] { 833 };
                case "member_initializer": return new int[] { 841, 843 };
                case "initializer_value": return new int[] { 857 };
                case "element_initializer": return new int[] { 864, 866 };
                case "member_declarator_list": return new int[] { 885 };
                case "member_declarator": return new int[] { 893, 895 };
                case "generic_dimension_specifier": return new int[] { 909, 914, 921 };
                case "anonymous_function_signature": return new int[] { 952 };
                case "right_arrow": return new int[] { 953, 1524, 2240, 2259, 2295, 2328 };
                case "anonymous_function_body": return new int[] { 954 };
                case "implicit_anonymous_function_parameter_list": return new int[] { 963 };
                case "explicit_anonymous_function_parameter": return new int[] { 969, 971 };
                case "from_clause": return new int[] { 995, 1016 };
                case "query_body": return new int[] { 996, 1070 };
                case "query_body_clause": return new int[] { 1006 };
                case "select_or_group_clause": return new int[] { 1012 };
                case "query_continuation": return new int[] { 1013 };
                case "let_clause": return new int[] { 1017 };
                case "where_clause": return new int[] { 1018 };
                case "combined_join_clause": return new int[] { 1019 };
                case "orderby_clause": return new int[] { 1020 };
                case "ordering": return new int[] { 1047, 1049 };
                case "statement": return new int[] { 1074, 1266 };
                case "local_variable_declaration": return new int[] { 1076, 1271, 1329 };
                case "local_constant_declaration": return new int[] { 1077 };
                case "embedded_statement": return new int[] { 1082, 1119, 1122, 1143, 1151, 1192, 1198, 1214 };
                case "simple_embedded_statement": return new int[] { 1086, 1248 };
                case "if_body": return new int[] { 1097, 1099 };
                case "switch_section": return new int[] { 1107 };
                case "for_initializer": return new int[] { 1131 };
                case "for_iterator": return new int[] { 1139 };
                case "catch_clauses": return new int[] { 1177 };
                case "finally_clause": return new int[] { 1178, 1181 };
                case "resource_acquisition": return new int[] { 1196 };
                case "pointer_type": return new int[] { 1211 };
                case "fixed_pointer_declarators": return new int[] { 1212 };
                case "statement_list": return new int[] { 1219, 1256 };
                case "local_variable_declarator": return new int[] { 1225, 1227 };
                case "local_variable_initializer": return new int[] { 1235 };
                case "local_variable_initializer_unsafe": return new int[] { 1240, 2054 };
                case "constant_declarators": return new int[] { 1245, 2248 };
                case "switch_label": return new int[] { 1251 };
                case "specific_catch_clause": return new int[] { 1290, 1291 };
                case "general_catch_clause": return new int[] { 1297, 1300 };
                case "exception_filter": return new int[] { 1310, 1316 };
                case "qualified_identifier": return new int[] { 1334 };
                case "namespace_body": return new int[] { 1335 };
                case "extern_alias_directive": return new int[] { 1359 };
                case "using_directive": return new int[] { 1369 };
                case "namespace_member_declaration": return new int[] { 1391 };
                case "namespace_declaration": return new int[] { 1396 };
                case "type_declaration": return new int[] { 1397 };
                case "attributes": return new int[] { 1400, 1430, 1502, 1607, 1619, 1626, 1644, 1653, 1675, 1688, 1694, 1755, 1821, 1843, 1907, 1912, 1921, 1949 };
                case "all_member_modifiers": return new int[] { 1403, 1505, 1758 };
                case "class_definition": return new int[] { 1406, 1533 };
                case "struct_definition": return new int[] { 1407, 1534 };
                case "interface_definition": return new int[] { 1408, 1535 };
                case "enum_definition": return new int[] { 1409, 1536 };
                case "delegate_definition": return new int[] { 1410, 1537 };
                case "type_parameter": return new int[] { 1420, 1422 };
                case "type_parameter_constraints_clause": return new int[] { 1452 };
                case "type_parameter_constraints": return new int[] { 1460 };
                case "constructor_constraint": return new int[] { 1462, 1469 };
                case "primary_constraint": return new int[] { 1463 };
                case "secondary_constraints": return new int[] { 1465 };
                case "class_member_declarations": return new int[] { 1492 };
                case "class_member_declaration": return new int[] { 1497 };
                case "common_member_declaration": return new int[] { 1508, 1761 };
                case "destructor_definition": return new int[] { 1509 };
                case "all_member_modifier": return new int[] { 1512 };
                case "constant_declaration": return new int[] { 1519 };
                case "typed_member_declaration": return new int[] { 1520 };
                case "event_declaration": return new int[] { 1521 };
                case "conversion_operator_declarator": return new int[] { 1522 };
                case "body": return new int[] { 1523, 2269, 2280, 2327 };
                case "constructor_declaration": return new int[] { 1530 };
                case "method_declaration": return new int[] { 1532, 1545 };
                case "indexer_declaration": return new int[] { 1543, 1547 };
                case "property_declaration": return new int[] { 1546 };
                case "operator_declaration": return new int[] { 1548 };
                case "field_declaration": return new int[] { 1549 };
                case "constant_declarator": return new int[] { 1552, 1554 };
                case "variable_declarator": return new int[] { 1564, 1566 };
                case "variable_initializer": return new int[] { 1574, 1795, 1797, 2235 };
                case "parameter_array": return new int[] { 1591, 1594 };
                case "fixed_parameters": return new int[] { 1592 };
                case "fixed_parameter": return new int[] { 1599, 1601 };
                case "parameter_modifier": return new int[] { 1610 };
                case "arg_declaration": return new int[] { 1613, 1728, 2321, 2323 };
                case "array_type": return new int[] { 1623 };
                case "accessor_modifier": return new int[] { 1629, 1647, 1656 };
                case "accessor_body": return new int[] { 1633, 1638, 1651, 1660 };
                case "set_accessor_declaration": return new int[] { 1634 };
                case "get_accessor_declaration": return new int[] { 1639 };
                case "remove_accessor_declaration": return new int[] { 1680 };
                case "add_accessor_declaration": return new int[] { 1684 };
                case "argument_list": return new int[] { 1734, 2341, 2347 };
                case "interface_type_list": return new int[] { 1744, 1832 };
                case "struct_member_declaration": return new int[] { 1747 };
                case "fixed_size_buffer_declarator": return new int[] { 1764 };
                case "variant_type_parameter": return new int[] { 1811, 1813 };
                case "variance_annotation": return new int[] { 1824 };
                case "interface_member_declaration": return new int[] { 1835 };
                case "type_parameter_list": return new int[] { 1854, 1887, 2147, 2162, 2283 };
                case "formal_parameter_list": return new int[] { 1858, 1874, 1891, 2206, 2253, 2273, 2287 };
                case "type_parameter_constraints_clauses": return new int[] { 1862, 1895, 2153, 2168, 2183, 2210, 2291 };
                case "interface_accessors": return new int[] { 1869, 1877 };
                case "enum_member_declaration": return new int[] { 1934, 1936 };
                case "global_attribute_target": return new int[] { 1958 };
                case "attribute_list": return new int[] { 1960, 1981 };
                case "keyword": return new int[] { 1966, 1987 };
                case "attribute_section": return new int[] { 1970 };
                case "attribute_target": return new int[] { 1976 };
                case "attribute": return new int[] { 1991, 1993 };
                case "attribute_argument": return new int[] { 2001, 2003 };
                case "fixed_pointer_declarator": return new int[] { 2038, 2040 };
                case "fixed_pointer_initializer": return new int[] { 2048 };
                case "boolean_literal": return new int[] { 2080 };
                case "string_literal": return new int[] { 2081 };
                case "interpolated_regular_string": return new int[] { 2091 };
                case "interpolated_verbatium_string": return new int[] { 2092 };
                case "interpolated_regular_string_part": return new int[] { 2098 };
                case "interpolated_verbatium_string_part": return new int[] { 2107 };
                case "interpolated_string_expression": return new int[] { 2115, 2121 };
                case "class_base": return new int[] { 2150 };
                case "class_body": return new int[] { 2156 };
                case "struct_interfaces": return new int[] { 2165 };
                case "struct_body": return new int[] { 2171 };
                case "variant_type_parameter_list": return new int[] { 2177, 2202 };
                case "interface_base": return new int[] { 2180 };
                case "interface_body": return new int[] { 2186 };
                case "enum_base": return new int[] { 2192 };
                case "enum_body": return new int[] { 2195 };
                case "_type": return new int[] { 2200 };
                case "variable_declarators": return new int[] { 2217, 2227 };
                case "member_name": return new int[] { 2220, 2230 };
                case "event_accessor_declarations": return new int[] { 2222 };
                case "accessor_declarations": return new int[] { 2232, 2256 };
                case "constructor_initializer": return new int[] { 2277 };
                case "method_member_name": return new int[] { 2282 };
                case "method_body": return new int[] { 2294 };
                case "overloadable_operator": return new int[] { 2319 };

                default: return null;
            }
        }
    }
}
